
name: Collect

on:
  schedule:
    # - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    - cron: "5,15,25,35,45,55 * * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install Requirements
        run: pip install requests
      - name: Running Collector
        run: python main.py
      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin master
          git add ./subs
          git checkout master
          git commit -m "✔️ $(date '+%Y-%m-%d %H:%M:%S') Collected"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
