name: Collect

on:
  schedule:
    # - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    - cron: "8,18,28,38,48,58 * * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install Requirements
        run: |
          pip install -r ./requirements.txt
      - name: Running Collector
        run: python main.py
      - uses: stefanzweifel/git-auto-commit-action@v5

